# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'
inhibit_all_warnings!

abstract_target 'polaris-ios' do
  use_frameworks!
  
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'SnapKit', '~> 5.0.0'

  target 'Polaris' do
  end
  
  target 'Polaris Beta' do
  end
  
end
